"""Shared helpers for the dashboard data-quality tests.

Checks live in per-table modules (test_*.py); this module holds only the
genuinely repeated machinery: CSV loading, path canonicalisation, cross-table
join helpers, and baseline drift comparison.
"""
from __future__ import annotations

import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

# --------------------------------------------------------------------------- #
# loading
# --------------------------------------------------------------------------- #

def sniff_delimiter(path: str | Path) -> str:
    """Return '|' for sqlite3 default output, ',' for CSV."""
    with open(path, newline="", encoding="utf-8", errors="ignore") as fh:
        first = fh.readline()
    return "|" if first.count("|") > first.count(",") else ","


def clean(value: str | None) -> str:
    """Strip whitespace and the quoting bqrs/sqlite add."""
    return (value or "").strip().strip('"').strip("'")


KERNEL_TOP_DIRS = {
    "arch", "block", "certs", "crypto", "drivers", "fs", "include", "init",
    "io_uring", "ipc", "kernel", "lib", "mm", "net", "rust", "samples",
    "scripts", "security", "sound", "tools", "usr", "virt",
}


def load_rows(path: str | Path, columns: list[str]) -> list[dict]:
    """Load a CSV into dicts keyed by `columns` (positional binding).
    Automatically skips a leading header row if present. Short rows are skipped."""
    delim = sniff_delimiter(path)
    rows: list[dict] = []
    with open(path, newline="", encoding="utf-8", errors="ignore") as fh:
        for idx, raw in enumerate(csv.reader(fh, delimiter=delim)):
            if len(raw) < len(columns):
                continue
            cleaned_first = clean(raw[0])
            # Skip CSV header row generated by `codeql bqrs decode` or sqlite
            if idx == 0 and (
                cleaned_first == columns[0]
                or cleaned_first in (
                    "col0", "cdc", "call_value", "call_site", "syscall",
                    "function_name", "definition", "struct_name", "func",
                    "config", "name", "type", "conditions", "macro_name",
                    "macroinvocation_name",
                )
            ):
                continue
            rows.append({c: clean(v) for c, v in zip(columns, raw)})
    return rows


def canonical_path(p: str) -> str:
    """Reduce a build-specific absolute path to a kernel-relative one."""
    p = clean(p)
    parts = [pt for pt in p.split("/") if pt]
    if parts and parts[0] in KERNEL_TOP_DIRS and not p.startswith("/usr/local") and not p.startswith("/usr/src"):
        return "/".join(parts)
    for marker in ("linux_v", "linux-"):
        if marker in p:
            after = p.split(marker, 1)[1]
            if "/" in after:
                return after.split("/", 1)[1].lstrip("/")
    for i, part in enumerate(parts):
        if i == 0 and part == "usr" and len(parts) > 1 and parts[1] in ("local", "src", "share", "home"):
            continue
        if part in KERNEL_TOP_DIRS and i < len(parts) - 1:
            return "/".join(parts[i:])
    return p.lstrip("/")


def is_int(value: str) -> bool:
    try:
        int(value)
        return True
    except (TypeError, ValueError):
        return False


# --------------------------------------------------------------------------- #
# reporting: measurements must be visible even when checks pass
# --------------------------------------------------------------------------- #

def report(title: str, lines: dict | list[tuple] | None = None) -> None:
    """Print a measurement block to stderr so it survives pytest capture."""
    print(f"\n--- {title} ---", file=sys.stderr)
    if isinstance(lines, dict):
        lines = list(lines.items())
    for item in (lines or []):
        if isinstance(item, (tuple, list)) and len(item) >= 2:
            key = str(item[0])
            value = "  ".join(str(x) for x in item[1:])
        else:
            key, value = str(item), ""
        print(f"    {key:<44} {value}", file=sys.stderr)


def pct(numerator: int, denominator: int) -> float:
    return 100.0 * numerator / denominator if denominator else 0.0


# --------------------------------------------------------------------------- #
# cross-table agreement
# --------------------------------------------------------------------------- #

def agreement(
    rows: list[dict],
    key_col: str,
    value_col: str,
    reference: dict[str, str],
) -> tuple[int, int, list[tuple]]:
    """Compare rows[value_col] against an independently-produced reference map
    keyed on rows[key_col]. Returns (checked, matched, sample_mismatches)."""
    checked = matched = 0
    mismatches: list[tuple] = []
    for row in rows:
        key = row[key_col]
        if key not in reference:
            continue
        checked += 1
        if row[value_col] == reference[key]:
            matched += 1
        elif len(mismatches) < 15:
            mismatches.append((key, row[value_col], reference[key]))
    return checked, matched, mismatches


# --------------------------------------------------------------------------- #
# baselines: recorded stats from a validated run, for drift detection
# --------------------------------------------------------------------------- #

def load_baseline(path: str | Path | None, table: str) -> dict:
    if not path or not Path(path).exists():
        return {}
    with open(path, encoding="utf-8") as fh:
        return json.load(fh).get(table, {})


def drift(observed: float, expected: float, tolerance: float) -> tuple[bool, str]:
    """True when |observed-expected| is within `tolerance` (absolute, same units)."""
    if expected is None:
        return True, "no baseline"
    delta = abs(observed - expected)
    ok = delta <= tolerance
    return ok, f"observed={observed:.3f} baseline={expected:.3f} delta={delta:.3f} tol={tolerance}"


def top_counts(rows: list[dict], col: str, n: int = 8) -> list[tuple]:
    return Counter(r[col] for r in rows).most_common(n)


def group_sets(rows: list[dict], key_col: str, value_col: str) -> dict[str, set]:
    out: dict[str, set] = defaultdict(set)
    for row in rows:
        out[row[key_col]].add(row[value_col])
    return dict(out)
