name: kernelCTF vuln verify
on:
  pull_request_target:
    types: [labeled]

  workflow_dispatch:
    inputs:
      prNumber:
        description: 'PR number to verify'
        required: true
jobs:
  vuln-verify:
    if: github.event.label.name == 'vuln-verify' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_REF: ${{ contains(github.event_name, 'workflow_') && format('refs/pull/{0}/merge', inputs.prNumber) || github.event.pull_request.head.sha }}
      PR_NUM: ${{ contains(github.event_name, 'workflow_') && inputs.prNumber || github.event.pull_request.number }}
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.KERNELCTF_GCS_SA_KEY }}'

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          sparse-checkout: kernelctf/vuln-verify

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ env.PR_REF }}
          path: pr
          sparse-checkout: pocs/linux/kernelctf

      - name: Checkout kernel-research
        uses: actions/checkout@v4
        with:
          repository: google/kernel-research
          path: kernel-research
          sparse-checkout: image_runner

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y expect build-essential flex bison bc libelf-dev libssl-dev cpio pahole
          pip install requests

      - name: Setup environment
        run: echo "IMAGE_RUNNER_DIR=${{ github.workspace }}/kernel-research/image_runner" >> $GITHUB_ENV

      - name: Determine submission folder
        id: determine_folder
        run: |
          FILES=$(gh pr view $PR_NUM --json files --jq '.files[] | .path')
          echo "Files in PR:"
          echo "$FILES"
          
          POC_FOLDER=$(echo "$FILES" | grep '^pocs/linux/kernelctf/' | cut -d/ -f1-4 | sort -u)
          if [ $(echo "$POC_FOLDER" | grep -c .) -ne 1 ]; then
            echo "Exactly one PoC folder must be found in pocs/linux/kernelctf/, but found:"
            echo "${POC_FOLDER:-<none>}"
            exit 1
          fi

          echo "folder=$POC_FOLDER" >> $GITHUB_OUTPUT
          echo "Found PoC folder: $POC_FOLDER"

      - name: Run vuln-verify
        if: steps.determine_folder.outputs.folder != ''
        run: |
          ./kernelctf/vuln-verify/verify.py "pr/${{ steps.determine_folder.outputs.folder }}"
