name: kernelCTF vuln verify
on:
  pull_request_target:
    types: [labeled]

  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to verify'
        required: true
jobs:
  vuln-verify:
    if: github.event.label.name == 'vuln-verify' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{ secrets.KERNELCTF_GCS_SA_KEY }}'

      - name: Fetch PR metadata
        id: pr_metadata
        run: |
          PR_NUMBER="${{ github.event.inputs.pr_number || github.event.pull_request.number }}"
          PR_DATA=$(gh pr view "$PR_NUMBER" --json headRepository,headRefName,headRepositoryOwner --jq '.headRepository.name, .headRefName, .headRepositoryOwner.login')
          readarray -t DATA <<< "$PR_DATA"
          echo "repo_full_name=${DATA[2]}/${DATA[0]}" >> $GITHUB_OUTPUT
          echo "head_ref=${DATA[1]}" >> $GITHUB_OUTPUT
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: master
          sparse-checkout: kernelctf/vuln-verify

      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.pr_metadata.outputs.repo_full_name }}
          ref: ${{ steps.pr_metadata.outputs.head_ref }}
          path: pr
          sparse-checkout: pocs/linux/kernelctf

      - name: Checkout kernel-research
        uses: actions/checkout@v4
        with:
          repository: google/kernel-research
          path: kernel-research
          sparse-checkout: image_runner

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y expect build-essential flex bison bc libelf-dev libssl-dev cpio pahole
          pip install requests

      - name: Setup environment
        run: echo "IMAGE_RUNNER_DIR=${{ github.workspace }}/kernel-research/image_runner" >> $GITHUB_ENV

      - name: Determine submission folder
        id: determine_folder
        run: |
          FILES=$(gh pr view ${{ steps.pr_metadata.outputs.pr_number }} --json files --jq '.files[] | .path')
          POC_FOLDER=$(echo "$FILES" | grep '^pocs/linux/kernelctf/' | cut -d/ -f1-4 | sort -u | head -n 1)
          echo $FILES
          
          if [ -z "$POC_FOLDER" ]; then
            echo "No added folders found in pocs/linux/kernelctf/"
            exit 1
          fi

          echo "folder=$POC_FOLDER" >> $GITHUB_OUTPUT
          echo "Found PoC folder: $POC_FOLDER"

      - name: Run vuln-verify
        if: steps.determine_folder.outputs.folder != ''
        run: |
          ./kernelctf/vuln-verify/verify.py "pr/${{ steps.determine_folder.outputs.folder }}"
