name: kernelCTF test upload
on:
  workflow_dispatch:
    inputs:
      runId:
        description: 'Workflow Run ID'
        type: string
        required: true
        default: '30268297225'
      artifactName:
        description: 'Artifact Name'
        type: string
        required: true
        default: 'lts2-6.12.98'

permissions: {}

jobs:
  upload:
    runs-on: ubuntu-24.04
    steps:
      - name: Download release
        uses: actions/download-artifact@v7
        with:
          name: ${{ inputs.artifactName }}
          path: ./kernelctf/releases/
          repository: google/security-research
          run-id: ${{ inputs.runId }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: '${{secrets.KERNELCTF_GCS_SA_KEY}}'

      - name: Upload release
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: kernelctf/releases
          destination: kernelctf-build/releases
          parent: false
          predefinedAcl: publicRead
          gzip: false # most of the files are compressed already, do not compress them again
          process_gcloudignore: false # removes warnings that .gcloudignore file does not exist
